name: gestion_clientes
description: Una aplicación para gestionar clientes y generar rótulos.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  _fe_analyzer_shared: ^67.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  material_color_utilities: ^0.8.0
  path_provider: ^2.0.11
  pdf: ^3.8.4
  printing: ^5.9.3
  web: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png